### ISSUE TITLE
Problem: The '--data' option requireѕ an argument.

### ISSUE THREAD

**Issue by tracure1337** [freecinc/freecinc-web#12]
```
Forge::BashCommandError at /generated_keys
ERROR: The '--data' option requireѕ an argument.
```

I start the docker image and can reach the landing page but as soon as I click generate keys I receive the error above.

What am I missing?

Thank you for this great interface.

**Comment by tracure1337** [comment]
I also tried adding the env variables but no dice unfortunately. 
But the web interface recognizes them.

**Comment by tracure1337** [comment]
```
HOSTNAME=djmitche-freecinc-web1
RUBY_DOWNLOAD_SHA256=8262e4663169c85787fdc9bfbd04d9eb86eb2a4b56d7f98373a8fcaa18e593eb
PUBLIC_HOSTNAME=freecinc-taskd
RUBY_VERSION=2.6.8
PWD=/etc/taskd/pki
SECRETS_DIR=/etc/taskd/pki
BUNDLE_APP_CONFIG=/usr/local/bundle
RUBY_MAJOR=2.6
HOME=/root
LANG=C.UTF-8
TASKDATA=/etc/taskd
BUNDLE_SILENCE_ROOT_WARNING=1
SALT=23812jvsl
GEM_HOME=/usr/local/bundle
TERM=xterm
APP_NAME=tasks
SHLVL=1
PKI_DIR=/etc/taskd/pki
PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TASKDDATA=/etc/taskd
_=/usr/bin/env
OLDPWD=/etc/taskd
```

I added the PKI dir manually after, because it wasn't there!?

```
root@djmitche-freecinc-web1:/app# taskd config server localhost:53589
Config file /etc/taskd/config modified.
root@djmitche-freecinc-web1:/app# taskd init
You must specify the 'server' variable before attempting a server start, for example:
  taskd config server localhost:53589

Created /etc/taskd/config
```

**Comment by tracure1337** [comment]
Alright. I got everything working!   I needed to confgure taskd and have it running as well.

**Comment by djmitche** [comment]
I'm curious what you're working on -- are you running the docker images locally?

The docker images expect to have the data directories mounted from elsewhere when run in a container (otherwise that data is lost when the container exits).  That's why the directory doesn't exist in the image.
