### ISSUE TITLE
freecinc.com: Form for Step 2 on generated keys page is broken.

### ISSUE THREAD

**Issue by errnoh** [freecinc/freecinc-web#8]
Generated forms look like: `action="httpss://freecinc.com/download/freecinc_ffffffff.key.pem"`. Changing the action to use `https` instead of `httpss` works as intended.

**Comment by rdlfoote** [comment]
Does not work for me if I change the link to https instead of httpss. I just get a page saying "Not Found" I also get a security warning asking me to confirm (insecure connection, could be read by a third party) before it sends me to the httpss page. I'm on Firefox 66.

**Comment by djmitche** [comment]
What URL gives you the security warning?

Note that the fix hasn't landed yet, so this is expected to still be an issue.

**Comment by djmitche** [comment]
Production seems to be fixed now as well.  Please note here if it's not working.
